services:
  jaeger:
    container_name: jeager
    image: jaegertracing/all-in-one:latest
    ports:
      - "6831:6831/udp"
      - "16686:16686"
    networks:
      - jaeg
    labels:
      NAME: "jaeger"
  intger_db:
    build: artifacts/cmd/mysql/.
    ports:
      - "3306:3306"
    container_name: intger_db
    environment:
      MYSQL_ROOT_PASSWORD: supasecret
      MYSQL_DATABASE: mysql_blogforge
      MYSQL_USER: forge-service
      MYSQL_PASSWORD: forgesecret
    networks:
      - db
    labels:
      NAME: intger_db
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 20s
      timeout: 10s
      retries: 40
  apid:
    build:
       dockerfile: artifacts/cmd/apid/.
       context: ./
    container_name: blogforge_apid
    environment:
      BASEPATH: /appdemon
      MYSQL_USER: forge-service
      MYSQL_PASSWORD: forgesecret
    ports:
      - "8080:8080"
    networks:
      - apid
      - db
      - jaeg
    depends_on:
      intger_db:
        condition: service_healthy
networks:
  db:
  apid:
  jaeg: